### ISSUE TITLE
Implement custom grouping

### ISSUE THREAD

**Issue by tomodutch** [CMTelecom/messaging-php#3]
I want to be able to add a customgrouping to a message to identity them later on.
https://docs.cmtelecom.com/bulk-sms/v1.0#/send_a_message%7Ccustom_grouping

**Comment by PallieterVerhoeven** [comment]
There is a merge request that implements this functionality.
https://github.com/CMTelecom/messaging-php/pull/4

**Comment by PallieterVerhoeven** [comment]
Merged: https://github.com/CMTelecom/messaging-php/releases/tag/v1.1.0
